### PR TITLE
New scenario (device-modal)

### PR DESCRIPTION
**Pull request by laozi999**
My best wishes! Happy phishing!

### CODE REVIEW

**Comment by laozi999** [comment]
@blackHatMonkey All done!

**Comment by blackHatMonkey** [comment]
@laozi999 Thanks :smile:. I will test it and let you know.

**Comment by laozi999** [comment]
Hi @blackHatMonkey, have you had a chance to go through the code yet?

**Comment by laozi999** [comment]
Feel free to update `framework7.min.js` and `kitchen-sink.js` to the latest version (if it has changed since)

https://github.com/nolimits4web/Framework7

**Comment by blackHatMonkey** [comment]
@laozi999 Sorry I was a bit busy. I will take a look at it as soon as possible :smile:.

**Comment by blackHatMonkey** [comment]
It's very nice but a couple of things after testing android version are:
1. Once you press the `show password` you can't un-select it
2. The `show advanced`  box doesn't show any more information

**Comment by blackHatMonkey** [comment]
Also you mentioned updating the `framework7.min.js` to the latest version [here](https://github.com/wifiphisher/extra-phishing-pages/pull/2#issuecomment-287543802) but I didn't see any commits updating it?

**Comment by laozi999** [comment]
To be honest I got lazy and didn't expect anyone to go through advanced settings.

In my opinion this scenario is ideal for iPhone when the captive portal pop-up fades in, it looks identical to the original WPA login form which fades in the same way.

Regarding framework7, I made this scenario a while ago so it might've had some updates since.

**Comment by blackHatMonkey** [comment]
@laozi999 Thanks for contributing :smile:.

**Pull request merged**
